### ISSUE TITLE
change order of sections on "detailed quality" page

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality.arc42.org-site#104]
„Directed Related Quality Requirements“
sollen VOR die beiden Kategorien „Related Qualities“ und „Related Quality Requirements“ 

z.B. https://quality.arc42.org/qualities/accessibility und die übrigen qualities.

**Comment by Per-Starke** [comment]
Also zuerst
- directly related requirements, dann
- related qualities, dann 
- related requirements?

**Comment by gernotstarke** [comment]
yes, exactly
