### ISSUE TITLE
Resource not found: S. Jamwal, Deepshikha Jamwal & Devanand Padha: Comparative Study

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality.arc42.org-site#111]
this pdf is not found: https://www.semanticscholar.org/paper/Comparative-Analysis-of-Different-Software-Quality-Jamwal-Jamwal/5ac9b66041dd4bbc5f01331edf2e6161010933a3#citing-papers

I originally downloaded it from https://enos.itcollege.ee/~nafurs/suvi2019/huvitavat/alternatiivid_FURPSile.pdf

**Comment by gernotstarke** [comment]
The citation is completely broken - in the source given above, different authors are given.

@martinweck I don't understand why you closed the issue...

**Comment by martinweck** [comment]
hm, ok that was a misunderstanding, I thought this was about the comparative study by Suman, whose link is correct, but it is about the local reference "jamwal" in 02-quality-models.md
I suggest that we should have either a reference in 70-references.md or a direct link, but not also references below a file. Moreover, it was helpful if issues like this one informs where a link is used that is broken. Ok, I have a look for that reference.

**Comment by martinweck** [comment]
Neuer Lösungsversuch: https://github.com/arc42/quality.arc42.org-site/pull/117

**Comment by gernotstarke** [comment]
that does the trick. Thanx @martinweck
