### ISSUE TITLE
Fix License Missmatch

### ISSUE THREAD

**Issue by PapaBravo** [arc42/quality.arc42.org-site#134]
Currently, the `LICENCE` file claims CC0-1.0 for this project while the `README.md` claims CC BY-SA 4.0. 

Please change either to reflect the intended license.

**Comment by gernotstarke** [comment]
I currently see cc-by-sa 4.0 as the best option for this kind of work - in case you don't have other proposals, I would change the files accordingly...

**Comment by gernotstarke** [comment]
thx Paul btw for letting me know.

**Comment by PapaBravo** [comment]
Yes I agree. cc-by-sa 4.0 is a good licence for this.
