### ISSUE TITLE
Fix references to 25010-2022 to the more correct 25010-2023

### ISSUE THREAD

**Issue by ddebree** [arc42/quality.arc42.org-site#156]
In the references section, the link refers to ISO 25010-2022 (https://quality.arc42.org/references/#iso-25010-2022). The ISO standard was released in 2023, so more accurately it should refer to 25010-2023.

**Comment by gernotstarke** [comment]
Per, here's an interesting one to fix: On the site we use both 25010-2022 and 25010-2023... the former shall be removed completely (so a global search/replace should do).

afaik the hyperlink in the references section pointing to the iso/IEC website seems ok, though.

@ddebree thanx for pointing out this (tiny) bug :-)

**Comment by ddebree** [comment]
I also thought it was a simple find-replace, but some qualities use definitions out of the ISO standard, so these definitions should be updated as the links are fixed. I put together #157 to start the process for the top-level qualities.

**Comment by Per-Starke** [comment]
@gernotstarke Regarding the last comment, is this still something I can / should do?

**Comment by Per-Starke** [comment]
@gernotstarke @ddebree Okidoki, feel free to re-assign me to the issue when I can help :)

**Comment by ddebree** [comment]
I will do the remaining updates in the next day or two, so you can leave this to me.

**Comment by ddebree** [comment]
Ok. Updates to the links are done. See #158. I did some spot-checks on the definitions and most seem correct.
