### ISSUE TITLE
new css style to distinguish between requirements and qualities, visually consistent

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality.arc42.org-site#61]
something like the greenish color from the requirements-scenario headings shall also be available as background, similar to the arc42-help class.

We need something like that:

```
<div class="quality-requirement" >
</div>
```

where:
* markdown is enabled per default (so we don't need the "markdown=1" in all occurences)
* bullet-list text has the same size as normal text
* bullet-lists have proper indentation, like shown here, especially follow-up lines in multi-line text does not left-aligh, but respect the indentation of the first line.  See image for an example.

![Image](https://user-images.githubusercontent.com/1233990/212547187-af17af2d-b56d-43c3-8f53-689d3c4a98d9.png)

**Comment by gernotstarke** [comment]
create color-names for these, to avoid hard-coding color codes in md-files (like I did in home.md)

**Comment by Per-Starke** [comment]
@gernotstarke mainly done, but need further explanation regarding your comment:
> create color-names for these, to avoid hard-coding color codes in md-files (like I did in home.md)
