### ISSUE TITLE
markdown processing on home.md

### ISSUE THREAD

**Issue by Per-Starke** [arc42/quality.arc42.org-site#63]
> "Explanations, Examples and Cross-References"

> explanations to (currently 81) _qualities_ of software systems and -architectures, which are blueish in color.
21 examples for specific quality **requirements**, which are greenish in color.

Markdown does not seem to be processed here, markdown="1" does not work either, this needs to be addressed?

**Comment by gernotstarke** [comment]
is fixed in current version

**Comment by gernotstarke** [comment]
<img width="793" alt="Screenshot 2023-01-17 um 08 29 41" src="https://user-images.githubusercontent.com/1233990/212835850-5877475a-9e58-484e-8396-39c72faf58ed.png">

**Comment by gernotstarke** [comment]
evtl the liquid filter "markdownify" could help
