### ISSUE TITLE
Change content of "Usable With Gloves"

### ISSUE THREAD

**Issue by Per-Starke** [arc42/quality.arc42.org-site#76]
This currently was, including the title, a copy of "Usable Despite Color Blindness", just the file was named differently. I moved it to the higher directory, [you can find it here](requirements/_posts/2999-01-20-usable-with-gloves-TO-BE-DONE.md) (after you accepted PR #75), I think the content here is not what it should be and that should be fixed / filled with the content that should actually go here (I can't do that, you know :D). After that you could, following the new directory structure, move it back to  `/requirements/usable/_posts ` instead of just having it located at  `/requirements/_posts `

**Comment by gernotstarke** [comment]
done
