### ISSUE TITLE
add link to status to all other sites

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality.arc42.org-site#85]

**Comment by gernotstarke** [comment]
done for docs.arc42.org, with nice status-icon :-)

**Comment by Per-Starke** [comment]
- [ ] quality
- [ ] docs
- [ ] de
- [ ] org
- [ ] faq

@gernotstarke any site missing?

**Comment by Per-Starke** [comment]
Maybe contact plausible about this? They seem quite "contactably" :D 
I'm still adding the status link to the other sites (in the footer), right?
