### ISSUE TITLE
re-organize examples: map to qualities instead of properties

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality.arc42.org-site#93]
the mapping of (the 8) properties to example-requirements is too unspecific.

Let's replace it by mapping examples to (low-level) qualities.

(suggested by @Hruschka )

**Comment by gernotstarke** [comment]
@Per-Starke as discussed f2f:

- [ ] clone "List of Qualities", so that every specific quality contains a list of related examples (with fa-lightbulb icon)

- [ ] "Examples of Quality Requirements": list example.title (as H3), and related qualities as list below

**Comment by Per-Starke** [comment]
@gernotstarke Within requirements, please write the related qualities without "-".
Do **NOT** remove the "-" within qualities and their related qualities. Just within requirements!

**Comment by gernotstarke** [comment]
that restriction is inconsistent - and I would very much like to remove it: Having exceptions in naming-conventions is difficult to understand and remember.

It will surprise new contributors.

I open a new issue for it.
