### ISSUE TITLE
Missing word in "Requirement: Near instant search

### ISSUE THREAD

**Issue by de313e** [arc42/quality.arc42.org-site#98]
On Page:
[Near instant search results](https://quality.arc42.org/requirements/near-instant-search-results)
Update 
`Metric: The system the first result within 500msec. Additional results might be added later.`
to
`Metric: The system shows/displays the first result within 500msec. Additional results might be added later.`

**Comment by gernotstarke** [comment]
@Per-Starke could you please update this requirement as proposed by @de313e  

thx Ufuk for pointing out this error
